# Generated by Django 3.2 on 2023-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('skill_requirement', models.TextField()),
                ('experience_requirement', models.IntegerField()),
            ],
        ),
    ]
